server:
  port: 6604

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: app1
          uri: http://localhost:8762
          predicates:
            - Path=/app1/**
          filters:
            - StripPrefix=1 #排除app1前缀
        - id: app2
          uri: http://localhost:8763
          predicates:
            - Path=/app2/**
          filters:
            - StripPrefix=1 #排除app2前缀
        - id: other
          uri: https://www.baidu.com
          predicates:
            - Path=/**